name: anonim_io
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^7.0.1
  fluttertoast: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^4.5.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  rxdart: ^0.27.7
  very_good_analysis: ^3.1.0

dev_dependencies:
  build_runner: ^2.3.3

  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
